kind: ConfigMap
apiVersion: v1
metadata:
  name: benchmark-config
  labels: {{- include "zeebe-benchmark.labels" . | nindent 4 }}
data: 
  benchmark-config.yaml: | {{ .Values.zeebe.config | toYaml | nindent 4 }}
  {{- if .Values.zeebe.profiling.enabled }}
  java-opts: -javaagent:/pyroscope/pyroscope.jar
  {{- end }}