{{- if .Values.leaderBalancing.enabled -}}
apiVersion: batch/v1
kind: CronJob
metadata:
  name: leader-balancer
  labels:
    {{- include "zeebe-benchmark.labels" . | nindent 4 }}
spec:
  schedule: {{ .Values.leaderBalancing.schedule | quote }}
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 3
  concurrencyPolicy: Forbid
  startingDeadlineSeconds: 120
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - image: "curlimages/curl:7.87.0"
              name: curl
              args: ["-L", "-v", "-X", "POST", "http://{{ .Release.Name }}-zeebe-gateway:9600/actuator/rebalance"]
          restartPolicy: OnFailure
{{- end }}