apiVersion: apps/v1
kind: Deployment
metadata:
  name: publisher
  labels:
    app: publisher
spec:
  selector:
    matchLabels:
      app: publisher
  replicas: {{ .Values.publisher.replicas }}
  template:
    metadata:
      labels:
        app: publisher
        app.kubernetes.io/component: zeebe-client
    spec:
      containers:
        - name: publisher
          image: "{{ .Values.global.image.repository }}/starter:{{ .Values.global.image.tag }}"
          imagePullPolicy: {{ .Values.global.image.pullPolicy }}
          env:
            - name: JDK_JAVA_OPTIONS
              value: >-
                -Dconfig.override_with_env_vars=true
                -Dapp.brokerUrl={{ .Release.Name }}-zeebe-gateway:26500
                -Dapp.starter.rate={{ .Values.publisher.rate }}
                -Dzeebe.client.requestTimeout=62000
                -XX:+HeapDumpOnOutOfMemoryError
                -Dapp.starter.bpmnXmlPath=bpmn/msg_one_task.bpmn
                -Dapp.starter.startViaMessage=true
            - name: LOG_LEVEL
              value: "warn"
          envFrom:
            - configMapRef:
                name: publisher-config
                optional: true
          resources:
            limits:
              cpu: 250m
              memory: 256Mi
            requests:
              cpu: 250m
              memory: 256Mi
          ports:
            - containerPort: 9600
              name: "http"